name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "ver/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    permissions:
      contents: write
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build RTP
        run: ./gradlew build

      - name: Prepare release notes and artifacts
        run: |
          chmod +x ./scripts/prepareRelease.sh
          ./scripts/prepareRelease.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

      - name: Upload RTP
        uses: actions/upload-artifact@main
        with:
          name: RTP 1.0-SNAPSHOT
          path: ./build/libs/RTP-1.0-SNAPSHOT.jar

      - name: Release RTP
        uses: softprops/action-gh-release@master
        with:
          name: "üîê RTP build ${{ env.BUILD_NUMBER }}"
          tag_name: "ver-1.0"
          files: |
            ./build/libs/RTP-1.0-SNAPSHOT.jar
          body_path: "./RELEASE.md"
          token: "${{ secrets.GITHUB_TOKEN }}"
          target_commitish: "${{ github.sha }}"
          draft: false
          prerelease: false